Repository DevLife-F1I4/DevLife, pull requests merged in 2024-04, with the labels that each got.

#18 ✨ feat/#10 : Comment CRUD 기능 구현 완료
  src/main/java/com/example/devlife/controller/CommentController.java
  src/main/java/com/example/devlife/dto/AddCommentRequest.java
  src/main/java/com/example/devlife/dto/UpdateCommentRequest.java
  src/main/java/com/example/devlife/entity/Board.java
  src/main/java/com/example/devlife/entity/Comment.java
  src/main/java/com/example/devlife/entity/User.java
  src/main/java/com/example/devlife/repository/board/BoardRepository.java
  src/main/java/com/example/devlife/repository/comment/CommentRepository.java
  src/main/java/com/example/devlife/service/comment/CommentService.java
Labels: ✨ FEAT

#22 ✨ feat/#21 : 관리자 API 기능 구현 완료
  src/main/java/com/example/devlife/controller/AdminController.java
  src/main/java/com/example/devlife/dto/UpdateUserGradeRequest.java
  src/main/java/com/example/devlife/entity/Grade.java
  src/main/java/com/example/devlife/entity/User.java
  src/main/java/com/example/devlife/service/admin/AdminService.java
Labels: ✨ FEAT

#23 ✨ Feat/#16 Thymeleaf 로그인 구현
  build.gradle
  src/main/java/com/example/devlife/config/SecurityConfig.java
  src/main/java/com/example/devlife/controller/AuthApiController.java
  src/main/java/com/example/devlife/controller/UserApiController.java
  src/main/java/com/example/devlife/controller/UserViewController.java
  src/main/java/com/example/devlife/dto/UserAccount.java
  src/main/java/com/example/devlife/dto/UserDto.java
  src/main/java/com/example/devlife/dto/UserInfoDto.java
  src/main/java/com/example/devlife/entity/User.java
  src/main/java/com/example/devlife/exception/DuplicateIdException.java
  src/main/java/com/example/devlife/exception/DuplicateNicknameException.java
  src/main/java/com/example/devlife/exception/UserNotFoundException.java
  src/main/java/com/example/devlife/repository/user/UserRepository.java
  src/main/java/com/example/devlife/security/JwtAuthenticationFilter.java
  src/main/java/com/example/devlife/security/JwtTokenProvider.java
  src/main/java/com/example/devlife/security/UserDetailsImpl.java
  src/main/java/com/example/devlife/security/UserDetailsServiceImpl.java
  src/main/java/com/example/devlife/service/AuthService.java
  src/main/java/com/example/devlife/service/user/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/static/js/login.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/mypage.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/valid.js
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/signup.html
Labels: ✨ FEAT

#25 ✨ feat #24: 로그아웃 기능 구현 완료
  src/main/java/com/example/devlife/config/SecurityConfig.java
  src/main/java/com/example/devlife/controller/AuthApiController.java
  src/main/java/com/example/devlife/service/admin/AdminService.java
  src/main/java/com/example/devlife/service/user/UserService.java
  src/main/resources/static/js/logout.js
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage.html
Labels: ✨ FEAT

#32 ☀️ merge : merge to main
  README.md
  build.gradle
  docker-compose.yml
  src/main/java/com/example/devlife/config/RedisConfig.java
  src/main/java/com/example/devlife/config/SecurityConfig.java
  src/main/java/com/example/devlife/config/SwaggerConfig.java
  src/main/java/com/example/devlife/controller/AdminController.java
  src/main/java/com/example/devlife/controller/AuthApiController.java
  src/main/java/com/example/devlife/controller/BoardController.java
  src/main/java/com/example/devlife/controller/CommentController.java
  src/main/java/com/example/devlife/controller/UserApiController.java
  src/main/java/com/example/devlife/controller/UserViewController.java
  src/main/java/com/example/devlife/dto/AddCommentRequest.java
  src/main/java/com/example/devlife/dto/AuthDto.java
  src/main/java/com/example/devlife/dto/BoardResponseDto.java
  src/main/java/com/example/devlife/dto/BoardWriteRequestDto.java
  src/main/java/com/example/devlife/dto/UpdateCommentRequest.java
  src/main/java/com/example/devlife/dto/UpdateUserGradeRequest.java
  src/main/java/com/example/devlife/dto/UserAccount.java
  src/main/java/com/example/devlife/dto/UserInfoDto.java
  src/main/java/com/example/devlife/entity/Board.java
  src/main/java/com/example/devlife/entity/Category.java
  src/main/java/com/example/devlife/entity/Comment.java
  src/main/java/com/example/devlife/entity/Grade.java
  src/main/java/com/example/devlife/entity/Role.java
  src/main/java/com/example/devlife/entity/User.java
  src/main/java/com/example/devlife/exception/DuplicateIdException.java
  src/main/java/com/example/devlife/exception/DuplicateNicknameException.java
  src/main/java/com/example/devlife/exception/UserNotFoundException.java
  src/main/java/com/example/devlife/repository/board/BoardRepository.java
  src/main/java/com/example/devlife/repository/comment/CommentRepository.java
  src/main/java/com/example/devlife/repository/user/UserRepository.java
  src/main/java/com/example/devlife/security/JwtAccessDeniedHandler.java
  src/main/java/com/example/devlife/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/devlife/security/JwtAuthenticationFilter.java
  src/main/java/com/example/devlife/security/JwtTokenProvider.java
  src/main/java/com/example/devlife/security/UserDetailsImpl.java
  src/main/java/com/example/devlife/security/UserDetailsServiceImpl.java
  src/main/java/com/example/devlife/service/AuthService.java
  src/main/java/com/example/devlife/service/RedisService.java
  src/main/java/com/example/devlife/service/admin/AdminService.java
  src/main/java/com/example/devlife/service/board/BoardService.java
  src/main/java/com/example/devlife/service/comment/CommentService.java
  src/main/java/com/example/devlife/service/user/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/bootstrap.yml
  src/main/resources/static/css/main.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/js/login.js
  src/main/resources/static/js/logout.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/mypage.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/valid.js
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/signup.html
Labels: ☀️ MERGE

#33 ✨ feat #17: 닉네임 수정 구현 완료
  src/main/java/com/example/devlife/controller/UserApiController.java
  src/main/java/com/example/devlife/controller/UserViewController.java
  src/main/java/com/example/devlife/security/JwtTokenProvider.java
  src/main/java/com/example/devlife/service/AuthService.java
  src/main/resources/application.yml
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/login.js
  src/main/resources/static/js/mypage.js
  src/main/resources/static/js/nickname.js
  src/main/resources/templates/edit-nickname.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/signup.html
Labels: ✨ FEAT

#45 ✨Feat/#44: 댓글 View 완성
  src/main/java/com/example/devlife/config/SecurityConfig.java
  src/main/java/com/example/devlife/controller/CommentController.java
  src/main/java/com/example/devlife/controller/CommentViewController.java
  src/main/java/com/example/devlife/dto/AddCommentRequest.java
  src/main/java/com/example/devlife/entity/Comment.java
  src/main/java/com/example/devlife/service/comment/CommentService.java
  src/main/resources/static/css/comment.css
  src/main/resources/static/js/comment.js
  src/main/resources/templates/comment/layout.html
  src/main/resources/templates/comment/list.html
Labels: ✨ FEAT

#47 ✨feat #46: 관리자 회원 관리 기능 구현
  src/main/java/com/example/devlife/config/SecurityConfig.java
  src/main/java/com/example/devlife/controller/AdminController.java
  src/main/java/com/example/devlife/controller/AdminViewController.java
  src/main/java/com/example/devlife/service/admin/AdminService.java
  src/main/resources/static/css/admin.css
  src/main/resources/static/js/admin.js
  src/main/resources/templates/admin/layout.html
  src/main/resources/templates/admin/main.html
Labels: ✨ FEAT

#58 🐛 fix #55: 관리자 페이지 링크 맞도록 수정
  src/main/java/com/example/devlife/config/SecurityConfig.java
  src/main/java/com/example/devlife/controller/AdminViewController.java
  src/main/resources/static/js/admin.js
  src/main/resources/templates/admin/layout.html
  src/main/resources/templates/mypage.html
Labels: 🐛 FIX

#59 🐛fix : redis 주석
  src/main/java/com/example/devlife/security/JwtTokenProvider.java
  src/main/java/com/example/devlife/service/AuthService.java
Labels: 🐛 FIX

#65 🐛fix : 로그아웃 문제 해결
  build.gradle
  src/main/java/com/example/devlife/config/SecurityConfig.java
  src/main/java/com/example/devlife/controller/AuthApiController.java
  src/main/java/com/example/devlife/controller/UserViewController.java
  src/main/java/com/example/devlife/service/AuthService.java
  src/main/resources/application.yml
  src/main/resources/static/js/logout.js
  src/main/resources/static/js/nickname.js
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/layout.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/update.html
  src/main/resources/templates/board/write.html
  src/main/resources/templates/edit-nickname.html
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/signup.html
Labels: 🐛 FIX

#73 🐛 fix #71: 관리자 계정 삭제 기능 오류 해결
  src/main/java/com/example/devlife/controller/BoardController.java
Labels: 🐛 FIX

#75 Update README.md
  README.md
Labels: 📝 UPDATE
